[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
runner = "probe-rs run --no-location --chip STM32F411RETx"

[profile.dev]
opt-level = "s"

[profile.release]
debug = 2

[env]
DEFMT_LOG = "info"
