10 print chr$(147)
20 print "     software defined retro rom"
30 print "      " + chr$(34) + "one rom to rule them all" + chr$(34)
40 print "========================================"
50 print "replace failed roms with a $2 stm32f4"
60 print "microcontroller. emulates 2364, 2332"
70 print "and 2316 roms across vintage systems."
80 print "----------------------------------------"
90 print "* stores up to 16 rom images"
100 print "* dynamic bank switching on the fly"
110 print "* same footprint as original roms"
120 print "* reflash in situ - no removal needed"
130 print "* software configurable chip selects"
140 print "* works on c64, vic-20, pet..."
150 print "----------------------------------------"
160 print "from kernel and basic to character sets,"
170 print "from diagnostics to application roms -"
180 print "one device handles them all seamlessly."
190 print ""
200 print "no expensive eprom programmers needed."
210 print "just 4 wires and 'make run' to program."
220 print "raspberry pi pico works as programmer."
230 print "========================================"
240 print "the power to rule all retro roms..."
250 goto 250